name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master

    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1

    - name: MSBuild
      working-directory: projectfiles/visualstudio-2019
      run: |
           msbuild fba_vs2010.vcxproj /m /property:Configuration=Release /property:Platform=x86
           msbuild fba_vs2010.vcxproj /m /property:Configuration=Release /property:Platform=x64
           msbuild fba_vs2010.vcxproj /m /property:Configuration=Debug /property:Platform=x64
           msbuild fba_vs2010.vcxproj /m /property:Configuration=Debug /property:Platform=x86
