name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Setup msys2
      run: choco install msys2
    - name: mingw build 
      run : |
            C:\tools\msys64\usr\bin\bash -lc "mingw32-make mingw510 -j5 RELEASEBUILD=1 SKIPDEPEND=1"
    - name: MSBuild
      working-directory: projectfiles/visualstudio-2019
      run: |
           msbuild fba_vs2010.vcxproj /m /property:Configuration=Release /property:Platform=x86 /verbosity:minimal
           msbuild fba_vs2010.vcxproj /m /property:Configuration=Release /property:Platform=x64 /verbosity:minimal


