name: C/C++ CI

on: [push]

jobs:
  codeartifact:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1  
    - name: upload vs x86 artifacts
      uses: actions/upload-artifact@v1
      with:
        name: fbn-code
        path: .
  buildvsx86:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: MSBuild x86
      working-directory: projectfiles/visualstudio-2019
      run: |
           msbuild fba_vs2010.vcxproj /m /property:Configuration=Release /property:Platform=x86 /verbosity:minimal
    - name: make artifacts
      run: |
           mkdir fbn-win32-vs
           cd fbn-win32-vs
           cp ../projectfiles/visualstudio-2019/Win32/Release/*.exe .
           cp ../fba.chm .
           cp ../*.zip .
           cp ../src/license.txt .
           cp ../whatsnew.html .
    - name: upload vs x86 artifacts
      uses: actions/upload-artifact@v1
      with:
        name: fbn-win32-vs
        path: fbn-win32-vs
  buildvsx64:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: MSBuild x64
      working-directory: projectfiles/visualstudio-2019
      run: |
           msbuild fba_vs2010.vcxproj /m /property:Configuration=Release /property:Platform=x64 /verbosity:minimal
    - name: make artifacts
      run: |
           mkdir fbn-x64-vs
           cd fbn-x64-vs
           cp ../projectfiles/visualstudio-2019/x64/Release/*.exe .
           cp ../fba.chm .
           cp ../*.zip .
           cp ../src/license.txt .
           cp ../whatsnew.html .
    - name: upload vs x64 artifacts
      uses: actions/upload-artifact@v1
      with:
        name: fbn-x64-vs
        path: fbn-x64-vs
  buildgcc:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Setup msys2
        uses: numworks/setup-msys2@v1
        with:
          msystem: MINGW32
      - name: mingw update 
        run : msys2do pacman -S --noconfirm --needed base-devel mingw-w64-i686-toolchain make perl nasm
      - name: mingw build
        run : msys2do make mingw510 -j9 RELEASEBUILD=1
      - name: make artifacts
        run: |
           mkdir fbn-x86-gcc
           cd fbn-x86-gcc
           cp ../fbneo.exe .
           cp ../fba.chm .
           cp ../*.zip .
           cp ../src/license.txt .
           cp ../whatsnew.html .
      - name: upload gcc x86 artifacts
        uses: actions/upload-artifact@v1
        with:
          name: fbn-x86-gcc
          path: fbn-x86-gcc    
  buildsdl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
         fetch-depth: 1
      - name: install dev tools
        run: |
             sudo apt-get -y update 
             sudo apt -y install libsdl1.2-dev
      - name: sdl build
        run: make sdl -j9 RELEASEBUILD=1 SKIPDEPEND=1
  buildosx:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
        with:
         fetch-depth: 1
      - name : do a perl
        run : brew install perl
      - name: build
        working-directory: projectfiles/xcode
        run: |
             xcodebuild -target Emulator -configuration Debug
        
        
